adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: product
adx_entityname: Products
adx_entitypermission_webrole:
- 417dab48-58cd-ee11-9079-0022483d3b93
adx_entitypermissionid: 85f25c41-58cd-ee11-9079-6045bd60843f
adx_read: true
adx_scope: 756150000
adx_write: false
